### ISSUE TITLE
maybe not an issue

### ISSUE THREAD

**Issue by josch09** [rilyu/mobac-ext#1]
Hi I tried your extended version of MOBAC but I failed miserably (perhaps I'm totally wrong and/or have totally misunderstood your readme.md - due to my non existing Chinese language skills)

Here is my use case:
- I have a local tile storage of 'old' downloaded google maps tiles of China.
- When I use this localTileFiles storage to create real maps (RMaps sqlite, osmand-sqlite etc.) with the original Mobac 1.9 version I always get maps with an offset of ca. 700m)
- So my hope was/is using your extended version to create maps in Mobac without this offset. 

Afaik downloaded China google maps tiles are not WGS-84 but GCJ-02. Therefore I thought I use your new <mapSpaceType> tag in my own local mapsource xml file:

```
<localTileFiles>
 <mapSpaceType>msMercatorGCJ02</mapSpaceType>
 <sourceType>DIR_ZOOM_X_Y</sourceType>
 <sourceFolder>/home/user/mobac18_china_tiles/Google Maps China</sourceFolder>
 <backgroundColor>#000000</backgroundColor>
</localTileFiles>
```
and then use this mapsource to generate the maps in your extended version of Mobac (RMaps sqlite, osmand sqlite format). But my generated maps still have the ~700m offset. 

Thanks in advance

**Comment by rilyu** [comment]
Set msMercatorGCJ02 role is to let MOBAC know the map projection, such as when loading gpx displayed in the correct position. 
If you want to convert your map to WGS-84 projection, you need to define a multi-layer map source and set forceMercator to true, like the following:

<?xml version="1.0" encoding="UTF-8"?>
<customMultiLayerMapSource>
	<name>newMap</name>
	<backgroundColor>#000000</backgroundColor>
	<forceMercator>true</forceMercator>
	<layers>
		<localTileFiles>
			<name>localMap</name>
			<mapSpaceType>msMercatorGCJ02</mapSpaceType>
			<sourceType>DIR_ZOOM_X_Y</sourceType>
			<sourceFolder><![CDATA[/home/user/mobac18_china_tiles/Google Maps China]]></sourceFolder>
		</localTileFiles>
	</layers>
</customMultiLayerMapSource>

**Comment by josch09** [comment]
I created a test map of the Guangzhou Baiyun International Aiport. 
Works like a charm!
Thanx
